//! Tool management, dynamic registry, and execution coordination with parallel/exclusive barriers and HITL approvals.

use async_trait::async_trait;
use dashmap::DashMap;
use futures::stream::{FuturesUnordered, StreamExt};
use serde_json::Value;
use std::sync::Arc;
use tokio::sync::{mpsc, RwLock};
use whale_adapters::ToolDefinition;
use whale_protocol::canonical::{new_item_id, CanonicalItem, CanonicalToolOutput};
use whale_protocol::events::AgentStreamEvent;

use crate::approval::{ApprovalDecision, ApprovalGate};
use crate::engine::RunProgress;
use crate::execution::{compile_tool_schema, CancellationToken, InvocationGuard, ToolContext};
use whale_protocol::contexts::{RunContextInfo, ToolContextInfo, ToolExecutionRecord};

/// Trait for defining executable agent tools.
#[async_trait]
pub trait ToolHandler: Send + Sync {
    /// Unique tool name.
    fn name(&self) -> &str;

    /// Detailed description of the tool behavior.
    fn description(&self) -> &str;

    /// JSON Schema for parameters expected by the tool.
    fn parameters(&self) -> Value;

    /// Whether this tool can safely run concurrently with other parallel-safe tools.
    /// Default is `true`. When `false`, requires exclusive execution barrier.
    fn supports_parallel(&self) -> bool {
        true
    }

    /// Whether this tool requires Human-in-the-Loop (HITL) approval before execution.
    /// Default is `false`.
    fn require_approval(&self) -> bool {
        false
    }

    /// Executes the tool with the given parsed JSON arguments.
    async fn execute(&self, arguments: Value) -> Result<CanonicalToolOutput, String>;

    /// Context-aware execution, with a compatible default for existing handlers.
    async fn execute_with_context(
        &self,
        context: ToolContext,
        arguments: Value,
    ) -> Result<(CanonicalToolOutput, bool), String> {
        if context.is_cancelled() {
            return Err("Execution cancelled before dispatch".into());
        }
        self.execute_with_status(arguments).await
    }

    /// Executes preserving a host's structured output and explicit failure flag.
    async fn execute_with_status(
        &self,
        arguments: Value,
    ) -> Result<(CanonicalToolOutput, bool), String> {
        self.execute(arguments).await.map(|output| (output, false))
    }
}

/// Dynamic, thread-safe tool registry.
#[derive(Default)]
pub struct ToolRegistry {
    tools: DashMap<String, Arc<dyn ToolHandler>>,
    parallel_barrier: Arc<RwLock<()>>,
}

impl ToolRegistry {
    /// Creates a new empty tool registry.
    pub fn new() -> Self {
        Self {
            tools: DashMap::new(),
            parallel_barrier: Arc::new(RwLock::new(())),
        }
    }

    /// Registers a tool handler.
    pub fn register(&self, tool: Arc<dyn ToolHandler>) -> Result<(), String> {
        compile_tool_schema(&tool.parameters())?;
        self.tools.insert(tool.name().to_string(), tool);
        Ok(())
    }

    /// Validates before publishing; an invalid schema never replaces an existing binding.
    pub fn try_register(&self, tool: Arc<dyn ToolHandler>) -> Result<(), String> {
        self.register(tool)
    }

    /// Unregisters a tool handler by name.
    pub fn unregister(&self, name: &str) -> Option<Arc<dyn ToolHandler>> {
        self.tools.remove(name).map(|(_, v)| v)
    }

    /// Gets a tool handler by name.
    pub fn get(&self, name: &str) -> Option<Arc<dyn ToolHandler>> {
        self.tools.get(name).map(|v| Arc::clone(v.value()))
    }

    /// Checks if a tool is registered.
    pub fn contains(&self, name: &str) -> bool {
        self.tools.contains_key(name)
    }

    /// Returns list of canonical `ToolDefinition`s for all registered tools.
    pub fn get_tool_definitions(&self) -> Vec<ToolDefinition> {
        self.tools
            .iter()
            .map(|entry| {
                let handler = entry.value();
                ToolDefinition::new(handler.name(), handler.description(), handler.parameters())
            })
            .collect()
    }
}

/// Coordinator for executing tool calls with parallel/exclusive barrier and HITL approval.
pub struct ToolExecutionCoordinator {
    registry: Arc<ToolRegistry>,
    approval_gate: Arc<ApprovalGate>,
}

impl ToolExecutionCoordinator {
    /// Creates a new ToolExecutionCoordinator.
    pub fn new(registry: Arc<ToolRegistry>, approval_gate: Arc<ApprovalGate>) -> Self {
        Self {
            registry,
            approval_gate,
        }
    }

    /// Returns reference to the approval gate.
    pub fn approval_gate(&self) -> &Arc<ApprovalGate> {
        &self.approval_gate
    }

    /// Returns reference to the tool registry.
    pub fn registry(&self) -> &Arc<ToolRegistry> {
        &self.registry
    }

    /// Executes a batch of tool call items generated by the LLM in the current step.
    ///
    /// Returns results in call order while observing each completion immediately.
    /// Enforces read/write locks on `parallel_barrier` according to `supports_parallel()`.
    /// Enforces HITL approval before execution if `require_approval()` is true.
    pub async fn execute_calls(
        &self,
        turn_id: &str,
        calls: Vec<CanonicalItem>,
        event_tx: Option<mpsc::Sender<AgentStreamEvent>>,
    ) -> Vec<CanonicalItem> {
        self.execute_calls_with_override_registry(turn_id, calls, None, event_tx)
            .await
    }

    /// Executes tool calls with an optional session-specific registry taking precedence over the global registry.
    pub async fn execute_calls_with_override_registry(
        &self,
        turn_id: &str,
        calls: Vec<CanonicalItem>,
        session_registry: Option<Arc<ToolRegistry>>,
        event_tx: Option<mpsc::Sender<AgentStreamEvent>>,
    ) -> Vec<CanonicalItem> {
        self.execute_calls_with_context(
            RunContextInfo {
                agent_name: None,
                thread_id: String::new(),
                turn_id: turn_id.into(),
                deadline_unix_ms: None,
            },
            CancellationToken::new(),
            Arc::new(RunProgress::default()),
            calls,
            session_registry,
            event_tx,
        )
        .await
    }

    pub async fn execute_calls_with_context(
        &self,
        run_context: RunContextInfo,
        cancellation: CancellationToken,
        progress: Arc<RunProgress>,
        calls: Vec<CanonicalItem>,
        session_registry: Option<Arc<ToolRegistry>>,
        event_tx: Option<mpsc::Sender<AgentStreamEvent>>,
    ) -> Vec<CanonicalItem> {
        self.execute_calls_with_journal(
            run_context,
            cancellation,
            progress,
            calls,
            session_registry,
            event_tx,
            None,
        )
        .await
        .expect("execution without a journal cannot produce a Store error")
    }

    /// Persist individual outcomes immediately, independently of batch result order.
    pub async fn execute_calls_with_journal(
        &self,
        run_context: RunContextInfo,
        cancellation: CancellationToken,
        progress: Arc<RunProgress>,
        calls: Vec<CanonicalItem>,
        session_registry: Option<Arc<ToolRegistry>>,
        event_tx: Option<mpsc::Sender<AgentStreamEvent>>,
        journal: Option<whale_store::SessionJournal>,
    ) -> Result<Vec<CanonicalItem>, whale_store::StoreError> {
        let mut pending = FuturesUnordered::new();
        for (index, call_item) in calls.into_iter().enumerate() {
            let registry = self.registry.clone();
            let session_registry = session_registry.clone();
            let barrier = session_registry
                .as_ref()
                .unwrap_or(&self.registry)
                .parallel_barrier
                .clone();
            let approval = self.approval_gate.clone();
            let run_context = run_context.clone();
            let cancellation = cancellation.clone();
            let progress = progress.clone();
            let event_tx = event_tx.clone();
            let journal = journal.clone();
            pending.push(async move {
                let turn_id = run_context.turn_id.clone();
                let mut result = Self::execute_single_call(
                    run_context,
                    cancellation,
                    progress,
                    call_item,
                    registry,
                    session_registry,
                    barrier,
                    approval,
                    event_tx,
                    journal.as_ref(),
                )
                .await?;
                if let Some(journal) = &journal {
                    let call_id = match &result {
                        CanonicalItem::ToolResult { call_id, .. } => call_id.clone(),
                        _ => unreachable!("tool execution always returns a ToolResult"),
                    };
                    result = journal
                        .commit(
                            &turn_id,
                            whale_store::RunMutation::ToolOutcome { call_id, result },
                        )
                        .await?
                        .result_item
                        .ok_or_else(|| {
                            whale_store::StoreError::Invalid(
                                "Tool outcome commit did not return its canonical result".into(),
                            )
                        })?;
                }
                Ok::<_, whale_store::StoreError>((index, result))
            });
        }
        let mut completed = Vec::new();
        while let Some(result) = pending.next().await {
            match result {
                Ok(result) => completed.push(result),
                Err(error) => {
                    cancellation.cancel();
                    return Err(error);
                }
            }
        }
        completed.sort_by_key(|(index, _)| *index);
        Ok(completed.into_iter().map(|(_, item)| item).collect())
    }

    async fn execute_single_call(
        run_context: RunContextInfo,
        cancellation: CancellationToken,
        progress: Arc<RunProgress>,
        call_item: CanonicalItem,
        registry: Arc<ToolRegistry>,
        session_registry: Option<Arc<ToolRegistry>>,
        barrier: Arc<RwLock<()>>,
        approval_gate: Arc<ApprovalGate>,
        event_tx: Option<mpsc::Sender<AgentStreamEvent>>,
        journal: Option<&whale_store::SessionJournal>,
    ) -> Result<CanonicalItem, whale_store::StoreError> {
        let (call_id, tool_name, raw_arguments, parsed_args) = match &call_item {
            CanonicalItem::ToolCall {
                call_id,
                name,
                raw_arguments,
                arguments,
                ..
            } => (
                call_id.clone(),
                name.clone(),
                raw_arguments.clone(),
                arguments.clone(),
            ),
            _ => {
                return Ok(CanonicalItem::tool_result(
                    "unknown",
                    CanonicalToolOutput::text("Item was not a ToolCall"),
                    true,
                ))
            }
        };
        let error_result = |message: String| {
            CanonicalItem::tool_result(call_id.clone(), CanonicalToolOutput::text(message), true)
        };
        let handler = match session_registry
            .as_ref()
            .and_then(|r| r.get(&tool_name))
            .or_else(|| registry.get(&tool_name))
        {
            Some(handler) => handler,
            None => {
                return Ok(error_result(format!(
                    "Tool '{}' not found in registry",
                    tool_name
                )))
            }
        };
        let mut final_args = match parsed_args {
            Some(args) => args,
            None => match serde_json::from_str::<Value>(&raw_arguments) {
                Ok(args) => args,
                Err(error) => {
                    return Ok(error_result(format!(
                        "Failed to parse tool arguments: {error}"
                    )))
                }
            },
        };
        let original_args = final_args.clone();
        let validator = match compile_tool_schema(&handler.parameters()) {
            Ok(validator) => validator,
            Err(error) => return Ok(error_result(error)),
        };
        if let Err(error) = validator.validate(&final_args) {
            return Ok(error_result(format!("Invalid tool arguments: {error}")));
        }
        if handler.require_approval() {
            let Some(tx) = &event_tx else {
                return Ok(error_result(
                    "Approval required but event stream is closed".into(),
                ));
            };
            match approval_gate
                .request_approval_with_context(
                    &run_context,
                    &cancellation,
                    &call_item,
                    &original_args,
                    None,
                    tx,
                )
                .await
            {
                Ok(ApprovalDecision::Accept) => {}
                Ok(ApprovalDecision::ModifyArguments { arguments }) => final_args = arguments,
                Ok(ApprovalDecision::Deny { reason }) => {
                    return Ok(error_result(format!(
                        "Execution denied by user: {}",
                        reason.unwrap_or_else(|| "User denied execution".into())
                    )))
                }
                Err(error) => return Ok(error_result(format!("Approval failed: {error}"))),
            }
        }
        if let Err(error) = validator.validate(&final_args) {
            return Ok(error_result(format!(
                "Invalid approved tool arguments: {error}"
            )));
        }
        let mut context = ToolContext::new(
            ToolContextInfo {
                run: run_context,
                call_id: call_id.clone(),
            },
            cancellation,
            event_tx.clone(),
        );
        if let Some(bridge) = approval_gate.interaction_bridge() {
            context = context.with_interaction_bridge(bridge);
        }
        let _invocation = InvocationGuard(context.clone());
        let execute = async {
            if context.is_cancelled() {
                return Ok((
                    CanonicalToolOutput::text("Execution cancelled before dispatch"),
                    true,
                ));
            }
            let record = ToolExecutionRecord {
                call_id: call_id.clone(),
                original_arguments: original_args,
                arguments: final_args.clone(),
            };
            // A committed intent is required before any host-side effect.
            if let Some(journal) = journal {
                journal
                    .commit(
                        &context.info.run.turn_id,
                        whale_store::RunMutation::DispatchIntent {
                            call_id: call_id.clone(),
                            execution: record.clone(),
                        },
                    )
                    .await?;
            }
            progress.record_execution(record.clone());
            if let Some(tx) = event_tx {
                if tx
                    .send(AgentStreamEvent::ToolExecutionStarted {
                        turn_id: context.info.run.turn_id.clone(),
                        call_id: record.call_id,
                        original_arguments: record.original_arguments,
                        arguments: record.arguments,
                    })
                    .await
                    .is_err()
                {
                    return Ok((
                        CanonicalToolOutput::text("Run event stream closed before dispatch"),
                        true,
                    ));
                }
            }
            if context.is_cancelled() {
                return Ok((
                    CanonicalToolOutput::text("Execution cancelled before dispatch"),
                    true,
                ));
            }
            Ok::<_, whale_store::StoreError>(
                match handler
                    .execute_with_context(context.clone(), final_args)
                    .await
                {
                    Ok(result) => result,
                    Err(error) => (CanonicalToolOutput::text(error), true),
                },
            )
        };
        let (output, is_error) = if handler.supports_parallel() {
            let _guard = barrier.read().await;
            execute.await?
        } else {
            let _guard = barrier.write().await;
            execute.await?
        };
        Ok(CanonicalItem::ToolResult {
            id: new_item_id(),
            call_id,
            output,
            is_error,
        })
    }
}
