//! Tool management, dynamic registry, and execution coordination with parallel/exclusive barriers and HITL approvals.

use std::sync::Arc;
use async_trait::async_trait;
use dashmap::DashMap;
use futures::stream::{FuturesOrdered, StreamExt};
use serde_json::Value;
use tokio::sync::{mpsc, RwLock};
use tracing::{debug, error, info, warn};
use whale_adapters::ToolDefinition;
use whale_protocol::canonical::{
    new_item_id, CanonicalItem, CanonicalToolOutput,
};
use whale_protocol::events::AgentStreamEvent;

use crate::approval::{ApprovalDecision, ApprovalGate};

/// Trait for defining executable agent tools.
#[async_trait]
pub trait ToolHandler: Send + Sync {
    /// Unique tool name.
    fn name(&self) -> &str;

    /// Detailed description of the tool behavior.
    fn description(&self) -> &str;

    /// JSON Schema for parameters expected by the tool.
    fn parameters(&self) -> Value;

    /// Whether this tool can safely run concurrently with other parallel-safe tools.
    /// Default is `true`. When `false`, requires exclusive execution barrier.
    fn supports_parallel(&self) -> bool {
        true
    }

    /// Whether this tool requires Human-in-the-Loop (HITL) approval before execution.
    /// Default is `false`.
    fn require_approval(&self) -> bool {
        false
    }

    /// Executes the tool with the given parsed JSON arguments.
    async fn execute(&self, arguments: Value) -> Result<CanonicalToolOutput, String>;
}

/// Dynamic, thread-safe tool registry.
#[derive(Default)]
pub struct ToolRegistry {
    tools: DashMap<String, Arc<dyn ToolHandler>>,
}

impl ToolRegistry {
    /// Creates a new empty tool registry.
    pub fn new() -> Self {
        Self {
            tools: DashMap::new(),
        }
    }

    /// Registers a tool handler.
    pub fn register(&self, tool: Arc<dyn ToolHandler>) {
        self.tools.insert(tool.name().to_string(), tool);
    }

    /// Unregisters a tool handler by name.
    pub fn unregister(&self, name: &str) -> Option<Arc<dyn ToolHandler>> {
        self.tools.remove(name).map(|(_, v)| v)
    }

    /// Gets a tool handler by name.
    pub fn get(&self, name: &str) -> Option<Arc<dyn ToolHandler>> {
        self.tools.get(name).map(|v| Arc::clone(v.value()))
    }

    /// Checks if a tool is registered.
    pub fn contains(&self, name: &str) -> bool {
        self.tools.contains_key(name)
    }

    /// Returns list of canonical `ToolDefinition`s for all registered tools.
    pub fn get_tool_definitions(&self) -> Vec<ToolDefinition> {
        self.tools
            .iter()
            .map(|entry| {
                let handler = entry.value();
                ToolDefinition::new(handler.name(), handler.description(), handler.parameters())
            })
            .collect()
    }
}

/// Coordinator for executing tool calls with parallel/exclusive barrier and HITL approval.
pub struct ToolExecutionCoordinator {
    registry: Arc<ToolRegistry>,
    parallel_barrier: Arc<RwLock<()>>,
    approval_gate: Arc<ApprovalGate>,
}

impl ToolExecutionCoordinator {
    /// Creates a new ToolExecutionCoordinator.
    pub fn new(registry: Arc<ToolRegistry>, approval_gate: Arc<ApprovalGate>) -> Self {
        Self {
            registry,
            parallel_barrier: Arc::new(RwLock::new(())),
            approval_gate,
        }
    }

    /// Returns reference to the approval gate.
    pub fn approval_gate(&self) -> &Arc<ApprovalGate> {
        &self.approval_gate
    }

    /// Returns reference to the tool registry.
    pub fn registry(&self) -> &Arc<ToolRegistry> {
        &self.registry
    }

    /// Executes a batch of tool call items generated by the LLM in the current step.
    ///
    /// Preserves exact dispatch order using `FuturesOrdered`.
    /// Enforces read/write locks on `parallel_barrier` according to `supports_parallel()`.
    /// Enforces HITL approval before execution if `require_approval()` is true.
    pub async fn execute_calls(
        &self,
        turn_id: &str,
        calls: Vec<CanonicalItem>,
        event_tx: Option<mpsc::Sender<AgentStreamEvent>>,
    ) -> Vec<CanonicalItem> {
        self.execute_calls_with_override_registry(turn_id, calls, None, event_tx).await
    }

    /// Executes tool calls with an optional session-specific registry taking precedence over the global registry.
    pub async fn execute_calls_with_override_registry(
        &self,
        turn_id: &str,
        calls: Vec<CanonicalItem>,
        session_registry: Option<Arc<ToolRegistry>>,
        event_tx: Option<mpsc::Sender<AgentStreamEvent>>,
    ) -> Vec<CanonicalItem> {
        let mut ordered_futures = FuturesOrdered::new();

        for call_item in calls {
            let registry = Arc::clone(&self.registry);
            let sess_reg = session_registry.clone();
            let barrier = Arc::clone(&self.parallel_barrier);
            let approval = Arc::clone(&self.approval_gate);
            let turn_id_owned = turn_id.to_string();
            let event_tx_opt = event_tx.clone();

            ordered_futures.push_back(async move {
                Self::execute_single_call(
                    &turn_id_owned,
                    call_item,
                    registry,
                    sess_reg,
                    barrier,
                    approval,
                    event_tx_opt,
                )
                .await
            });
        }

        let mut results = Vec::new();
        while let Some(result_item) = ordered_futures.next().await {
            results.push(result_item);
        }
        results
    }

    async fn execute_single_call(
        turn_id: &str,
        call_item: CanonicalItem,
        registry: Arc<ToolRegistry>,
        session_registry: Option<Arc<ToolRegistry>>,
        barrier: Arc<RwLock<()>>,
        approval_gate: Arc<ApprovalGate>,
        event_tx: Option<mpsc::Sender<AgentStreamEvent>>,
    ) -> CanonicalItem {
        let (call_id, tool_name, raw_arguments, parsed_args) = match &call_item {
            CanonicalItem::ToolCall {
                call_id,
                name,
                raw_arguments,
                arguments,
                ..
            } => (call_id.clone(), name.clone(), raw_arguments.clone(), arguments.clone()),
            _ => {
                return CanonicalItem::ToolResult {
                    id: new_item_id(),
                    call_id: "unknown".to_string(),
                    output: CanonicalToolOutput::text("Item was not a ToolCall"),
                    is_error: true,
                };
            }
        };

        // 1. Lookup tool in session registry first, then global registry
        let handler = match session_registry
            .as_ref()
            .and_then(|r| r.get(&tool_name))
            .or_else(|| registry.get(&tool_name))
        {
            Some(h) => h,
            None => {
                let err_msg = format!("Tool '{}' not found in registry", tool_name);
                warn!("{}", err_msg);
                return CanonicalItem::ToolResult {
                    id: new_item_id(),
                    call_id,
                    output: CanonicalToolOutput::text(err_msg),
                    is_error: true,
                };
            }
        };

        // 2. Parse arguments (or use pre-parsed)
        let mut final_args = match parsed_args {
            Some(args) => args,
            None => match serde_json::from_str::<Value>(&raw_arguments) {
                Ok(v) => v,
                Err(e) => {
                    let err_msg = format!("Failed to parse tool arguments: {}", e);
                    warn!("{}", err_msg);
                    return CanonicalItem::ToolResult {
                        id: new_item_id(),
                        call_id,
                        output: CanonicalToolOutput::text(err_msg),
                        is_error: true,
                    };
                }
            },
        };

        // 3. Check HITL approval if required
        if handler.require_approval() {
            if let Some(ref tx) = event_tx {
                info!("Tool '{}' ({}) requires approval, requesting...", tool_name, call_id);
                match approval_gate
                    .request_approval(turn_id, &call_item, None, tx)
                    .await
                {
                    Ok(ApprovalDecision::Accept) => {
                        debug!("Approval accepted for {}", call_id);
                    }
                    Ok(ApprovalDecision::ModifyArguments { arguments }) => {
                        debug!("Approval accepted with modified arguments for {}", call_id);
                        final_args = arguments;
                    }
                    Ok(ApprovalDecision::Deny { reason }) => {
                        let reason_msg = reason.unwrap_or_else(|| "User denied execution".to_string());
                        info!("Approval denied for {}: {}", call_id, reason_msg);
                        return CanonicalItem::ToolResult {
                            id: new_item_id(),
                            call_id,
                            output: CanonicalToolOutput::text(format!("Execution denied by user: {}", reason_msg)),
                            is_error: true,
                        };
                    }
                    Err(e) => {
                        error!("Approval request failed for {}: {}", call_id, e);
                        return CanonicalItem::ToolResult {
                            id: new_item_id(),
                            call_id,
                            output: CanonicalToolOutput::text(format!("Approval failed: {}", e)),
                            is_error: true,
                        };
                    }
                }
            } else {
                return CanonicalItem::ToolResult {
                    id: new_item_id(),
                    call_id,
                    output: CanonicalToolOutput::text("Approval required but event stream is closed"),
                    is_error: true,
                };
            }
        }

        // 4. Concurrency barrier: acquire read or write lock based on tool safety
        let (output, is_error) = if handler.supports_parallel() {
            let _read_guard = barrier.read().await;
            match handler.execute(final_args).await {
                Ok(out) => (out, false),
                Err(err) => (CanonicalToolOutput::text(err), true),
            }
        } else {
            // Exclusive lock barrier
            let _write_guard = barrier.write().await;
            match handler.execute(final_args).await {
                Ok(out) => (out, false),
                Err(err) => (CanonicalToolOutput::text(err), true),
            }
        };

        CanonicalItem::ToolResult {
            id: new_item_id(),
            call_id,
            output,
            is_error,
        }
    }
}
