//! Canonical types for the Whale AI SDK conversation protocol.
//!
//! Provides a standardized intermediate representation (IR) for LLM conversations,
//! abstracting differences between OpenAI, Claude (Anthropic), Gemini, and local models.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Unique identifier for a canonical message item.
pub type ItemId = String;

/// Helper function to generate a new item ID.
pub fn new_item_id() -> ItemId {
    Uuid::new_v4().to_string()
}

/// The phase of an assistant message.
///
/// Models often produce intermediate commentary or thinking before delivering the final answer.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessagePhase {
    /// Intermediate chain-of-thought commentary, planning, or progress notes.
    Commentary,
    /// The final user-facing response.
    #[default]
    FinalAnswer,
}

/// Multi-modal content block supported in canonical messages.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CanonicalContent {
    /// Plain text content.
    Text { text: String },
    /// Image content with mime type and either base64 data or a URI.
    Image {
        mime_type: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        data: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        uri: Option<String>,
    },
    /// Audio content with mime type and optional raw/base64 data or URI.
    Audio {
        mime_type: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        data: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        uri: Option<String>,
    },
}

impl CanonicalContent {
    /// Creates a new text content block.
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text { text: text.into() }
    }

    /// Creates a new image content block from a URI.
    pub fn image_uri(mime_type: impl Into<String>, uri: impl Into<String>) -> Self {
        Self::Image {
            mime_type: mime_type.into(),
            data: None,
            uri: Some(uri.into()),
        }
    }

    /// Creates a new image content block from base64 data.
    pub fn image_base64(mime_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self::Image {
            mime_type: mime_type.into(),
            data: Some(data.into()),
            uri: None,
        }
    }
}

/// Canonical representation of tool output.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CanonicalToolOutput {
    /// Simple string / text output from tool execution.
    Text { text: String },
    /// Structured JSON data returned by the tool.
    Structured { data: serde_json::Value },
    /// Complex multi-modal output blocks (e.g. text + images produced by a chart tool).
    Blocks { blocks: Vec<CanonicalContent> },
}

impl CanonicalToolOutput {
    /// Creates a text output.
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text { text: text.into() }
    }

    /// Creates a structured JSON output.
    pub fn structured(data: serde_json::Value) -> Self {
        Self::Structured { data }
    }

    /// Creates a multi-block output.
    pub fn blocks(blocks: Vec<CanonicalContent>) -> Self {
        Self::Blocks { blocks }
    }
}

/// Canonical items representing the discrete units of a conversation turn.
///
/// Tagged internally with `"type"` and `"snake_case"` representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CanonicalItem {
    /// Message sent by the human user.
    UserMessage {
        id: ItemId,
        content: Vec<CanonicalContent>,
    },

    /// Message generated by the AI assistant.
    AssistantMessage {
        id: ItemId,
        content: Vec<CanonicalContent>,
        phase: MessagePhase,
    },

    /// Explicit reasoning / chain-of-thought block (Anthropic extended thinking, OpenAI reasoning summary, etc.)
    Reasoning {
        id: ItemId,
        /// The reasoning/thinking text content.
        thinking: String,
        /// Cryptographic signature or verification token if provided by provider (e.g. Anthropic thinking signature).
        #[serde(skip_serializing_if = "Option::is_none")]
        signature: Option<String>,
        /// Opaque encrypted reasoning token if returned by provider.
        #[serde(skip_serializing_if = "Option::is_none")]
        encrypted_content: Option<String>,
    },

    /// Tool / function call invocation request from the model.
    ToolCall {
        id: ItemId,
        /// Tool call identifier (as referenced in tool results).
        call_id: String,
        /// Optional namespace (e.g., "bash", "mcp:filesystem", "host").
        #[serde(skip_serializing_if = "Option::is_none")]
        namespace: Option<String>,
        /// The name of the tool/function to invoke.
        name: String,
        /// Parsed JSON arguments if valid JSON.
        #[serde(skip_serializing_if = "Option::is_none")]
        arguments: Option<serde_json::Value>,
        /// Raw unparsed string arguments as streamed by LLM.
        raw_arguments: String,
    },

    /// Result of executing a tool call.
    ToolResult {
        id: ItemId,
        /// Matches the `call_id` of the originating `ToolCall`.
        call_id: String,
        /// The output payload.
        output: CanonicalToolOutput,
        /// True if execution resulted in an error.
        is_error: bool,
    },
}

impl CanonicalItem {
    /// Returns the ID of the item.
    pub fn id(&self) -> &str {
        match self {
            Self::UserMessage { id, .. } => id,
            Self::AssistantMessage { id, .. } => id,
            Self::Reasoning { id, .. } => id,
            Self::ToolCall { id, .. } => id,
            Self::ToolResult { id, .. } => id,
        }
    }

    /// Convenience constructor for user text message.
    pub fn user_text(text: impl Into<String>) -> Self {
        Self::UserMessage {
            id: new_item_id(),
            content: vec![CanonicalContent::text(text)],
        }
    }

    /// Convenience constructor for assistant text message.
    pub fn assistant_text(text: impl Into<String>, phase: MessagePhase) -> Self {
        Self::AssistantMessage {
            id: new_item_id(),
            content: vec![CanonicalContent::text(text)],
            phase,
        }
    }

    /// Convenience constructor for reasoning block.
    pub fn reasoning(
        thinking: impl Into<String>,
        signature: Option<String>,
        encrypted_content: Option<String>,
    ) -> Self {
        Self::Reasoning {
            id: new_item_id(),
            thinking: thinking.into(),
            signature,
            encrypted_content,
        }
    }

    /// Convenience constructor for tool call.
    pub fn tool_call(
        call_id: impl Into<String>,
        namespace: Option<String>,
        name: impl Into<String>,
        arguments: Option<serde_json::Value>,
        raw_arguments: impl Into<String>,
    ) -> Self {
        Self::ToolCall {
            id: new_item_id(),
            call_id: call_id.into(),
            namespace,
            name: name.into(),
            arguments,
            raw_arguments: raw_arguments.into(),
        }
    }

    /// Convenience constructor for tool result.
    pub fn tool_result(
        call_id: impl Into<String>,
        output: CanonicalToolOutput,
        is_error: bool,
    ) -> Self {
        Self::ToolResult {
            id: new_item_id(),
            call_id: call_id.into(),
            output,
            is_error,
        }
    }
}
