//! Streaming event definitions and token usage metrics.
//!
//! Provides granular real-time feedback during an agent turn execution.

use serde::{Deserialize, Serialize};

use crate::canonical::{CanonicalItem, ItemId, MessagePhase};

/// Token usage metrics for LLM generation.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct UsageMetrics {
    /// Number of prompt tokens fed to the model.
    pub input_tokens: u64,
    /// Number of completion tokens generated by the model.
    pub output_tokens: u64,
    /// Tokens used for internal reasoning / thinking.
    #[serde(default)]
    pub reasoning_tokens: u64,
    /// Tokens written to KV cache during prompt caching.
    #[serde(default)]
    pub cache_creation_input_tokens: u64,
    /// Tokens read from KV cache during prompt caching.
    #[serde(default)]
    pub cache_read_input_tokens: u64,
}

impl UsageMetrics {
    /// Total tokens consumed across prompt and output.
    pub fn total_tokens(&self) -> u64 {
        self.input_tokens + self.output_tokens
    }
}

/// Agent streaming events emitted during turn processing.
///
/// Tagged with `"type"` and serialized in `"snake_case"`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentStreamEvent {
    /// A new agent turn has started.
    TurnStarted {
        turn_id: String,
        thread_id: String,
    },

    /// A new canonical item (message, reasoning, tool call) has started.
    ItemStarted {
        turn_id: String,
        item_id: ItemId,
        item_type: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        phase: Option<MessagePhase>,
    },

    /// Incremental text delta for an assistant message or commentary.
    TextDelta {
        turn_id: String,
        item_id: ItemId,
        delta: String,
    },

    /// Incremental reasoning/thinking delta.
    ReasoningDelta {
        turn_id: String,
        item_id: ItemId,
        delta: String,
    },

    /// Signature or security verification attached to reasoning block upon completion.
    ReasoningSignature {
        turn_id: String,
        item_id: ItemId,
        signature: String,
    },

    /// Incremental chunk of tool call arguments.
    ToolCallDelta {
        turn_id: String,
        item_id: ItemId,
        call_id: String,
        /// Partial raw argument string delta.
        delta: String,
    },

    /// An item has completed and is finalized into a CanonicalItem.
    ItemCompleted {
        turn_id: String,
        item: CanonicalItem,
    },

    /// Human-in-the-loop approval is requested before executing a tool or action.
    ApprovalRequested {
        turn_id: String,
        request_id: String,
        tool_call: CanonicalItem,
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },

    /// The agent turn has completed successfully.
    TurnCompleted {
        turn_id: String,
        thread_id: String,
        usage: UsageMetrics,
    },

    /// The agent turn encountered a fatal error.
    TurnFailed {
        turn_id: String,
        thread_id: String,
        error_code: String,
        error_message: String,
    },
}
